defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: chimpance99

development:
  database: ipmep_development
  socket: /tmp/mysql.sock
  <<: *defaults

test: &test
  database: ipmep_test
  socket: /tmp/mysql.sock
  <<: *defaults

production:
  host: localhost
  database: ipmep_production
  <<: *defaults

cucumber:
  <<: *test
